version: '3.9'

services:
  artly-api:
    container_name: artly-api
    restart: always
    image: node:20.10.0
    ports:
      - '4001:3007'
    volumes:
      - ./:/usr/src/artly
    working_dir: /usr/src/artly

    networks:
      - monorepo-network

    #for prod
    command: bash -c "npm install && npm run build && npm run start:prod"

  artly-batch:
    container_name: artly-batch
    restart: unless-stopped
    image: node:20.10.0

    ports:
      - '4002:3008'
    volumes:
      - ./:/usr/src/artly
    working_dir: /usr/src/artly

    #for prod
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
