version: '3.9'

services:
  artly-api:
    container_name: artly-api
    restart: always
    image: node:20.10.0
    ports:
      - '3005:3005'
    volumes:
      - ./:/usr/src/artly
      - /usr/src/artly/node_modules
    working_dir: /usr/src/artly
    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  artly-batch:
    container_name: artly-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - '3006:3006'
    volumes:
      - ./:/usr/src/artly
      - /usr/src/artly/node_modules
    working_dir: /usr/src/artly
    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
