version: '3.9'

services:
  artly-api:
    container_name: artly-api
    restart: always
    image: node:20.10.0
    ports:
      - '4001:3007'
    volumes:
      - ./:/usr/src/artly
      - /usr/src/artly/node_modules # Prevent host node_modules interference
    working_dir: /usr/src/artly
    networks:
      - monorepo-network
    # UPDATED COMMAND - use the new script
    command: bash -c "npm install && npm run docker:prod"

  artly-batch:
    container_name: artly-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - '4002:3008'
    volumes:
      - ./:/usr/src/artly
      - /usr/src/artly/node_modules
    working_dir: /usr/src/artly
    networks:
      - monorepo-network

    command: bash -c "npm install && npm run docker:prod:batch"

networks:
  monorepo-network:
    driver: bridge
